### ISSUE TITLE
Add support to launch Activities for Active Edge

### ISSUE THREAD

**Issue by jtothe4n** [DirtyUnicorns/android_external_google#1]
Good job on adding support for Active Edge and even custom actions on AOSP!

Got a bunch of requests already adding support for Edge Sense Plus  [XDA Thread](https://forum.xda-developers.com/pixel-3-xl/themes/app-21st-oct-edge-sense-plus-1-10-0-t3856788) DU and other AOSP roms.
Since Edge Sense Plus provides activities to be able to process forwarded squeeze events it would be handy
if you could implement a custom squeeze action to launch an Activity.
That way people could launch also other desired custom apps

**Comment by BoredOutOfMyGit** [comment]
Thanks! @jtothe4n 

We'll look into it and try to implement this as well! :+1:

**Comment by BoredOutOfMyGit** [comment]
https://twitter.com/_DirtyUnicorns_/status/1096655427620818944

**Comment by jtothe4n** [comment]
One user messaged me today saying he does not see the Edge Sense Plus squeeze activities.
Don't have a Pixel device, so can't confirm.
Just checked the commit though, using [PackageManager.getInstalledApplications(PackageManager.GET_META_DATA](https://github.com/DirtyUnicorns/android_external_google/blob/758feefd79dc02e202caa8944a4ada61894533ec/src/com/android/systemui/elmyra/actions/AppPicker.java#L91) just lists the first launch activity for each app.

Edge Sense Plus has three of them though:

`           <activity
            android:name="eu.duong.edgesenseplus.MainActivity"
            android:label="@string/app_name"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="stateAlwaysHidden">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name="eu.duong.edgesenseplus.SinglePressActivity"
            android:excludeFromRecents="true"
            android:label="@string/singlepress_action"
            android:launchMode="singleInstance"
            android:noHistory="true"
            android:theme="@android:style/Theme.Translucent.NoTitleBar">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name="eu.duong.edgesenseplus.LongPressActivity"
            android:excludeFromRecents="true"
            android:label="@string/longpress_action"
            android:launchMode="singleInstance"
            android:noHistory="true"
            android:theme="@android:style/Theme.Translucent.NoTitleBar">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
`

using:

`
 PackageManager pm = getPackageManager();
        Intent intent = new Intent("android.intent.action.MAIN");
        intent.addCategory("android.intent.category.HOME");
        ResolveInfo homescreenInfo = pm .resolveActivity(intent,
                PackageManager.MATCH_DEFAULT_ONLY);
`

instead lists all of them.

Also   [getLaunchIntentForPackage](https://github.com/DirtyUnicorns/android_external_google/blob/758feefd79dc02e202caa8944a4ada61894533ec/src/com/android/systemui/elmyra/actions/CustomActions.java#L108) won't work.
Needs to be something like:

`
Intent intent=new Intent();
intent.setComponent(new ComponentName(packagename, activityname));
startActivity(intent);
`
